name: "On Tag Deploy on GitHub"

env:
  REPO_NAME: "nhentai_archivist"
  RUST_VERSION: "1.86"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  initialisation:
    name: "Initialisation"
    runs-on: ubuntu-latest

    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
      TODAY: ${{ steps.today.outputs.TODAY }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Tag"
        id: tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - name: "Get Date"
        id: today
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  build_linux:
    name: "Build Linux Executable"
    needs: initialisation
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-unknown-linux-gnu

      - name: "Build"
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: "Upload Build Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: ./target/x86_64-unknown-linux-gnu/release/${{ env.REPO_NAME }}

  create_release:
    name: "Create GitHub Release"
    needs: [initialisation, build_linux]
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: "Create Release"
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "${{ needs.initialisation.outputs.TODAY }} ${{ env.REPO_NAME }} ${{ needs.initialisation.outputs.TAG }}"
          draft: false
          prerelease: false

  upload_release_asset:
    name: "Upload Linux Binary to Release"
    needs: [initialisation, create_release]
    runs-on: ubuntu-latest

    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: ./dist

      - name: "Upload Asset"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./dist/${{ env.REPO_NAME }}
          asset_name: "${{ needs.initialisation.outputs.TODAY }} ${{ env.REPO_NAME }} ${{ needs.initialisation.outputs.TAG }} linux"
          asset_content_type: application/octet-stream
